package com.dermaCare.customerService.entity;
import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "payments")
public class Payment {

    @Id    
    private String id;
    private String transactionId;  // autogenerated in service
    private String userId;
    private String doctorId;
    private String clinicId;
    private String bookingId;
    private double amount;
    private String paymentMethod;
    private String paymentStatus;
    private LocalDateTime timestamp;  // autogenerated in service
    private String currency;
    private String userEmail;
    private String userMobile;
    private String billingName;
    private String billingAddress;
    private GatewayResponse gatewayResponse;
}

